<style>
  label {
    float: left;
    width: 200px;
  }
  input {
    margin-bottom: 10px;
    width: 30%;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Cập nhật Bài viết</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo base_url() ?>"><i class="fa fa-laptop"></i> Home</a></li>
    <li><a href="<?php echo base_url() ?>news">Bài viết</a></li>
    <li class="active">Cập nhật</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-xs-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">Thông tin</h3>
        </div><!-- /.box-header -->
        <?php echo $this->flash->output() ?>
        <!-- form start -->
        <form role="form" action="" method="post" enctype="multipart/form-data">
          <div class="box-body">
            <label>Tên bài viết</label>
            <input type="text" name="name" value=" <?php echo $news->name ?>" placeholder=" Tên bài viết ..."><br>
            <label>Tags</label>
            <input type="text" name="tag" value=" <?php echo $news->tag ?>" placeholder=" Tag ..."><br>
            <label>Danh mục</label>
            <select name="category">
              <option value="">Danh mục ...</option>
              <?php
                foreach ($data['category'] as $key => $value ) { 
                  $tab = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                  if ($value['lever'] == 1) {
                    $name = '<b>'.$value['name'].'</b>';
                  } else {
                    $name = $tab.$value['name'];
                  }
                  $selected = '';
                  if ($news->category == $value['id']) {
                    $selected = 'selected';
                  }
                  echo '<option '.$selected.' value="'.$value['id'].'">'.$name.'</option>';
                }
               ?>
            </select><br><br>
            <label>Nội dung</label><br><br>
            <textarea name="info" placeholder=" Nội dung bài viết ..."><?php echo $news->info ?></textarea>
            <script type="text/javascript">CKEDITOR.replace('info');</script>
            <br>        
            <label>Ảnh đại diện</label>(.png, .jpg, .jpeg)
            <input type="file" name="image" value="">
            <?php 
              if ($news->image) {
                $date = date('m-d-Y',strtotime($news->date));
                echo '<label>&nbsp;</label>';
                echo '<img src="'.base_url().'uploads/news/'.$date.'/'.$news->image.'" alt="" width="200"><br>';
              }
             ?>
          </div><!-- /.box-body -->
          <div class="box-footer">
            <label> &nbsp;</label>
            <button type="submit" class="btn btn-primary">Cập nhật</button>
            <button type="reset" class="btn btn-default">Hủy</button>
          </div>
        </form>
      </div><!-- /.box -->
    </div><!--/.col (left) -->
    <!-- right column -->
  </div>