<!DOCTYPE html>
<html class="bg-black">
  <head>
    <meta charset="UTF-8">
    <?php echo $this->tag->getTitle() ?>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="<?php echo base_url() ?>/skin/admin/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
  </head>
  <body class="bg-black">
    <div class="form-box" id="login-box">
      <div class="header">Sign In</div>
      <form action="" method="post">
        <div class="body bg-gray">
        <?php echo $this->flash->output(); ?>
          <div class="form-group">
            <input type="text" name="user" class="form-control" value="<?php echo isset($_POST['user']) ? $_POST['user'] : '' ?>" placeholder="User name ..."/>
          </div>
          <div class="form-group">
            <input type="password" name="password" class="form-control" placeholder="Password ..."/>
          </div>
          <div class="form-group">
            <input type="checkbox" name="remember_me"/> Remember me
          </div>
        </div>
        <div class="footer">
          <button type="submit" class="btn bg-olive btn-block">Sign me in</button>
          <p><a href="#">I forgot my password</a></p>
        </div>
      </form>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
  </body>
</html>