<style>
  label {
    float: left;
    width: 200px;
  }
  input {
    margin-bottom: 10px;
    width: 30%;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Tạo mới người dùng</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo base_url() ?>"><i class="fa fa-laptop"></i> Home</a></li>
    <li><a href="<?php echo base_url() ?>user">Người dùng</a></li>
    <li class="active">Tạo mới</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-xs-12">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">Thông tin</h3>
        </div><!-- /.box-header -->
        <?php echo $this->flash->output() ?>
        <!-- form start -->
        <form role="form" action="" method="post" enctype="multipart/form-data">
          <div class="box-body">
              <label>User</label>
              <input type="text" name="user" value="<?php echo isset($_POST['user']) ? $_POST['user'] : '' ?>" placeholder=" User ..."> (*)<br>
              <label>Tên</label>
              <input type="text" name="name" value="<?php echo isset($_POST['name']) ? $_POST['name'] : '' ?>" placeholder=" Tên ..."><br>
              <label>Mật khẩu</label>
              <input type="password" name="password" value="<?php echo isset($_POST['password']) ? $_POST['password'] : '' ?>" placeholder=" Mật khẩu ..."> (*)<br>
              <label>Nhập lại mật khẩu</label>
              <input type="password" name="password_re" value="<?php echo isset($_POST['password_re']) ? $_POST['password_re'] : '' ?>" placeholder=" Nhập lại mật khẩu ..."> (*)<br>
              <label>Email</label>
              <input type="email" name="email" value="<?php echo isset($_POST['email']) ? $_POST['email'] : '' ?>" placeholder=" Email ..."> (*)<br>
              <label>Địa chỉ</label>
              <input type="text" name="address" value="<?php echo isset($_POST['address']) ? $_POST['address'] : '' ?>" placeholder=" Địa chỉ ..."><br>
              <label>Số điện thoại</label>
              <input type="text" name="phone" value="<?php echo isset($_POST['phone']) ? $_POST['phone'] : '' ?>" placeholder=" (+84) ..."><br>
              <label>Role</label>
                <select name="role">
                  <option value="3">Member</option>
                  <option value="2">Admin</option>
                  <?php
                    if ($_user['role'] == 1) echo '<option value="1">Super Admin</option>';
                   ?>
                </select><br><br>
              <label>Ảnh đại diện</label>(.png, .jpg, .jpeg)
              <input type="file" name="image" value="">
              <label>&nbsp;</label>
              <span>(*) Thông tin bắt buộc</span>
          </div><!-- /.box-body -->
          <div class="box-footer">
            <label> &nbsp;</label>
            <button type="submit" class="btn btn-primary">Tạo mới</button>
            <button type="reset" class="btn btn-default">Hủy</button>
          </div>
        </form>
      </div><!-- /.box -->
    </div><!--/.col (left) -->
    <!-- right column -->
  </div>