<style>
  label {
    float: left;
    width: 200px;
  }
  input {
    margin-bottom: 10px;
    width: 30%;
  }
</style>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Cập nhật thông tin Người dùng</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo base_url() ?>"><i class="fa fa-desktop"></i> Home</a></li>
    <li><a href="<?php echo base_url() ?>user">Người dùng</a></li>
    <li class="active">Cập nhật người dùng</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">Thông tin</h3>
        </div><!-- /.box-header -->
        <?php echo $this->flash->output() ?>
        <!-- form start -->
        <form role="form" action="" method="post" enctype="multipart/form-data">
          <div class="box-body">
              <label>User</label>
              <input type="text" name="user" value="<?php echo $user->user ?>"><br>
              <label>Tên</label>
              <input type="text" name="name" value="<?php echo $user->name ?>"><br>
              <label>Email</label>
              <input type="text" name="email" value="<?php echo $user->email ?>"><br>
              <label>Địa chỉ</label>
              <input type="text" name="address" value="<?php echo $user->address ?>"><br>
              <label>Số điện thoại</label>
              <input type="text" name="phone" value="<?php echo $user->phone ?>"><br>
              <label>Role</label>
                <select name="role">
                  <option value="3" <?php if ($user->role == 3) echo 'selected' ?>>Member</option>
                  <option value="2" <?php if ($user->role == 2) echo 'selected' ?>>Admin</option>
                  <?php
                    $selected = '';
                    if ($user->role == 1) $selected = 'selected'; 
                    if ($_user['role'] == 1) echo '<option value="1" '.$selected.'>Super Admin</option>';
                   ?>
                </select><br><br>
              <label>Ảnh đại diện</label>
              <input type="file" name="image" value="">
              <?php 
                if ($user->image) {
                  $date = date('m-d-Y',strtotime($user->date));
                  echo '<label>&nbsp;</label>';
                  echo '<img src="'.base_url().'uploads/users/'.$date.'/'.$user->image.'" alt="" width="100"><br>';
                }
               ?>
          </div><!-- /.box-body -->
          <div class="box-footer">
            <label> &nbsp;</label>
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-default">Cancel</button>
          </div>
      </div><!-- /.box -->
    </div><!--/.col (left) -->
    <!-- right column -->
    <div class="col-md-6">
      <!-- general form elements disabled -->
      <div class="box box-info">
        <div class="box-header">
          <h3 class="box-title">Đổi mật khẩu</h3>
        </div><!-- /.box-header -->
        <!-- form start -->
          <div class="box-body">
            <label>Mật khẩu mới</label>
            <input type="password" name="password_new" value="<?php echo isset($_POST['password_new']) ? $_POST['password_new'] : '' ?>" placeholder=" Mật khẩu mới"><br>
            <label>Nhập lại mật khẩu</label>
            <input type="password" name="password_re" value="<?php echo isset($_POST['password_re']) ? $_POST['password_re'] : '' ?>" placeholder=" Nhập lại mật khẩu"><br>
          </div><!-- /.box-body -->
        </form>
      </div><!-- /.box -->
    </div><!--/.col (right) -->
  </div>