<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <?php echo $this->tag->getTitle(); ?>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Theme style -->
    <link href="<?php echo base_url(); ?>skin/admin/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <!-- DATA TABLES -->
    <link href="<?php echo base_url(); ?>skin/admin/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
    <!-- Bootstrap 3.3.1 -->
    <link href="<?php echo base_url(); ?>skin/admin/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- FontAwesome 4.2.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Ckeditor -->
    <script src="<?php echo base_url(); ?>ckeditor/ckeditor.js" type="text/javascript"></script>
  </head>
  <body class="skin-blue fixed">
    <div class="wrapper">
      <!-- header logo: style can be found in header.less -->
      <header class="main-header">
        <!-- Logo -->
        <a href="<?php echo base_url(); ?>" class="logo" target="_blank">Website</a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 4 messages</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo base_url(); ?>skin/admin/img/user2-160x160.jpg" class="img-circle" alt="User Image"/>
                          </div>
                          <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li><!-- end message -->
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo base_url(); ?>skin/admin/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo base_url(); ?>skin/admin/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo base_url(); ?>skin/admin/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Sales Department
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="<?php echo base_url(); ?>skin/admin/img/user4-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Reviewers
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-bell-o"></i>
                  <span class="label label-warning">10</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 10 notifications</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="ion ion-ios-people info"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning danger"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users warning"></i> 5 new members joined
                        </a>
                      </li>

                      <li>
                        <a href="#">
                          <i class="ion ion-ios-cart success"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="ion ion-ios-person danger"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->
              <li class="dropdown tasks-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="header">You have 9 tasks</li>
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Create a nice theme
                            <small class="pull-right">40%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">40% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Some task I need to do
                            <small class="pull-right">60%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">60% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Make beautiful transitions
                            <small class="pull-right">80%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">80% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?php 
                    if ($_user['image'] !=null) {
                      $date = date('m-d-Y',strtotime($_user['date']));
                      echo '<img src="'.base_url().'uploads/users/'.$date.'/'.$_user['image'].'" alt="'.$_user['image'].'" class="user-image">';
                    } else {
                      echo '<img src="'.base_url().'skin/admin/img/user.png" class="user-image" alt="User Image"/>';
                    }
                   ?>                  
                  <span class="hidden-xs"><?php echo $_user['name'] ?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="<?php echo base_url() ?>login/end" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- search form -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search..."/>
              <span class="input-group-btn">
                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <?php 
            $controller = $this->router->getControllerName();
           ?>
          <ul class="sidebar-menu">
            <li <?php if ($controller == 'admin') echo 'class="active"' ?> title="admin">
              <a href="<?php echo base_url() ?>admin"><i class="fa fa-desktop"></i> <span>Home</span></i></a>
            </li>
            <li <?php if ($controller == 'user') echo 'class="active"' ?> title="user">
              <a href="<?php echo base_url() ?>user"><i class="fa fa-users"></i> <span>Người dùng</span></a>
            </li>
            <li <?php if ($controller == 'category') echo 'class="active"' ?> title="category">
              <a href="<?php echo base_url() ?>category"><i class="fa fa-tasks"></i> <span>Danh mục</span></a>
            </li>
            <li <?php if ($controller == 'news') echo 'class="active"' ?> title="news">
              <a href="<?php echo base_url() ?>news"><i class="fa fa-pencil"></i> <span>Bài viết</span></a>
            </li>
            <li>
              <a href=""><i class="fa fa-calendar"></i> <span>Lịch</span></a>
            </li>
            <li>
              <a href=""><i class="fa fa-envelope"></i> <span>Mailbox</span><small class="label pull-right bg-yellow">12</small></a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper">
        <?php echo $this->getContent(); ?>
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          	<strong>Dev <a href="https://www.facebook.com/BoGia4404">JosT</a></strong>
        </div>
        <strong>Copyright &copy; 2015 <a href="<?php echo base_url(); ?>">giaoxutraigao.com</a></strong> All rights reserved.
      </footer>
    </div><!-- ./wrapper -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/jquery.min.js"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/jquery-ui.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/app.min.js" type="text/javascript"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/demo.js" type="text/javascript"></script>
    <script src="<?php echo base_url(); ?>skin/admin/plugins/datatables/jquery.dataTables.js" type="text/javascript"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/app-old.js" type="text/javascript"></script>
    <script src="<?php echo base_url(); ?>skin/admin/js/app.js" type="text/javascript"></script>
    <!-- Turn active -->
    <script>
      var controller = '<?php echo $this->router->getControllerName() ?>';        
      var currentUrl = '<?php echo base_url() ?>' + controller;
      // Turn acitve
      $(document).ready( function() {
        $('.turn-active').click(function(){
          var id    = $(this).attr('title');
          var val   = id.split('-');
          var check = confirm('Bạn chắc chắn muốn thay đổi ?');
          if (check == true) {
            $.ajax({
              url: currentUrl + '?',
              type: "POST",
              data:  'id=' + val[0] + '&active=' + val[1],
              async: false,
              success: function() {
              }
            });
          alert('Cập nhật thành công !');
          }
        });
        $('.turn-menu').click(function(){
          var id    = $(this).attr('title');
          var val   = id.split('-');
          var check = confirm('Bạn chắc chắn muốn thay đổi ?');
          if (check == true) {
            $.ajax({
              url: currentUrl + '?',
              type: 'POST',
              data: 'id=' + val[0] + '&menu=' + val[1],
              async: false,
              success: function() {
              } 
            });
          alert('Cập nhật thành công !');
          }
        });
      });
      // Popup edit
      $('a#show-popup').click(function(){
        var cate_edit = $(this).attr('title');
        // alert(cate_edit);
        $.ajax({
          ulr     : currentUrl + '?',
          type    : 'POST',
          data    : 'cate_edit=' + cate_edit,
          async   : false,
          success : function(kq) { 
            // alert(kq);
          }
        });
      });
      
      <!-- page script -->
      $(function () {
        $("#example1").dataTable();
        $('#example2').dataTable({
          "bPaginate": true,
          "bLengthChange": false,
          "bFilter": false,
          "bSort": true,
          "bInfo": true,
          "bAutoWidth": false
        });
      });
    </script>
  </body>
</html>