<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Quản lý Danh mục</h1>
  <ol class="breadcrumb">
    <li><a href="<?php echo base_url() ?>admin"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<?php echo base_url() ?>category">Danh mục</a></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <div id="popup-bg"></div>
  <div class="row">
    <!-- left column -->
    <div class="col-md-6">
      <!-- general form elements -->
      <div class="box box-primary">
        <div class="box-header">
          <h3 class="box-title">Bảng dữ liệu</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th class="align" width="5%">No.</th>
                <th class="align">Name</th>
                <th class="align" width="5%">Menu</th>
                <th class="align" width="5%">Active</th>
              </tr>
            </thead>
            <tbody>
            <?php
              if ($data['category']) {
                foreach ($data['category'] as $key => $value ) {
                  $tab = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                  if ($value['lever'] == 1) {
                    $name = '<b>'.$value['name'].'</b>';
                  } else {
                    for ($i=2; $i <= $value['lever']; $i++) { 
                      $tab .= $tab;
                    }
                    $name = $tab.$value['name'];
                  }
             ?>
              <tr>  
                <td class="align"><?php echo $key +1 ?></td>
                <td><a href="#" id="show-popup" class="edit" title="<?php echo $value['id'] ?>"><?php echo $name ?></a></td>
                <?php echo $this->helper->menu($value['id'], $value['menu']) ?>
                <?php echo $this->helper->check($value['id'], $value['active']) ?>
              </tr>
            <?php } }?>
            </tbody>
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
      <!-- Input addon -->
      <div class="box box-info" id="popup">
        <div class="box-header" id="popup-header">
          <h3 class="box-title">Cập nhật danh mục</h3>
          <!-- tools box -->
          <div class="pull-right box-tools">
            <button class="btn btn-info" title="Close" id="close"><i class="fa fa-times"></i></button>
          </div><!-- /. tools -->
        </div>
        <div class="box-body">
        <!-- form start -->
        <form role="form" action="" method="post">
          <div class="form-group">
            <label>Tên danh mục</label>
            <input type="text" class="form-control" name="name" value="<?php echo $category; ?>" placeholder="Tên danh mục ...">
            <!-- <p id="kq"></p> -->
          </div>
          <div class="form-group">
            <label>Danh mục</label>
            <select multiple name="parent" class="form-control select-category">
              <option value="0">Danh mục gốc</option>
              <?php
                foreach ($data['category'] as $key => $value ) { 
                  $tab = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                  if ($value['lever'] == 1) {
                    $name = '<b>'.$value['name'].'</b>';
                  } else {
                    $name = $tab.$value['name'];
                  }
                  echo '<option value="'.$value['id'].'">'.$name.'</option>';
                }
               ?>
            </select>
          </div>
          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Cập nhật</button>
          </div>
        </form>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div><!--/.col (left) -->
    <!-- right column -->
    <div class="col-md-6">
      <!-- general form elements disabled -->
      <div class="box box-info">
        <div class="box-header">
          <h3 class="box-title">Tạo mới danh mục</h3>
        </div><!-- /.box-header -->
        <?php echo $this->flash->output() ?>
        <!-- form start -->
        <form role="form" action="" method="post">
          <div class="box-body">
            <div class="form-group">
              <label>Tên danh mục</label>
              <input type="text" class="form-control" name="name" value="" placeholder="Tên danh mục ...">
            </div>
            <div class="form-group">
              <label>Danh mục</label>
              <select multiple name="parent" class="form-control select-category">
                <option value="0">Danh mục gốc</option>
                <?php
                  foreach ($data['category'] as $key => $value ) { 
                    $tab = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                    if ($value['lever'] == 1) {
                      $name = '<b>'.$value['name'].'</b>';
                    } else {
                      $name = $tab.$value['name'];
                    }
                    echo '<option value="'.$value['id'].'">'.$name.'</option>';
                  }
                 ?>
              </select>
            </div>
          </div><!-- /.box-body -->

          <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div><!-- /.box -->
    </div><!--/.col (right) -->
  </div>   <!-- /.row

    