<div class="current-page">
	<i class="fa fa-home"></i> <i class="fa fa-angle-double-right"></i> <?php echo $category->name ?>
</div> <!-- / .current-page -->
<section id="ccr-category-2">
	<?php 
		foreach ($page->items as $key => $value) {
			if ($key == 0) {
	 ?>		
	<div class="ccr-category-featured">
		<div class="ccr-thumbnail"><img src="<?php echo base_url()."uploads/news/".$this->date->mdY($value->date)."/".$value->image ?>" alt="<?php echo $value->image ?>" height="260" title="<?php echo $value->name ?>"></div>
		<article>
		<h4><?php echo $value->name ?></h4>
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php $this->string->read_more($value->info, 600) ?>
			<div class="like-comment-readmore">
				<a href="#" class="like"><i class="fa fa-thumbs-o-up"></i> 08</a>
				<a href="#"  class="comments"><i class="fa fa-comments-o"></i> 49</a>
				<a class="read-more" href="<?php echo base_url()."bai-viet/".$value->id."-".$this->string->replace($value->name) ?>">Đọc tiếp</a>
			</div> <!-- /.like-comment-readmore -->
		</article>
	</div> <!-- /#ccr-category-featured -->
	<div id="ccr-categpry-latest-post">
		<ul class="ccr-category-post">
	<?php } else { ?>
			<li>
				<div class="ccr-thumbnail">
					<img src="<?php echo base_url()."uploads/news/".$this->date->mdY($value->date)."/".$value->image ?>" alt="<?php echo $value->image ?>" height="191">
					<p><a href="<?php echo base_url()."bai-viet/".$value->id."-".$this->string->replace($value->name) ?>">Đọc tiếp</a></p>
				</div>
				<h5><a href="<?php echo base_url()."bai-viet/".$value->id."-".$this->string->replace($value->name) ?>"><?php $this->string->read_more($value->name, 25) ?></a></h5>
			</li>
	<?php } } ?>
		</ul> <!-- /.ccr-latest-post -->
	</div> <!-- /.ccr-latest-post-gallery -->
	<nav class="nav-paging">
		<ul>
			
			<?php
				if ($page->current == $page->first) {
					echo '<li><i class="fa fa-chevron-left"></i></li>';
				} else {
					echo '<li><a href="'.base_url().'danh-muc/'.$category->id.'-'.$this->string->replace($category->name).'?page='.$page->before.'"><i class="fa fa-chevron-left"></i></a></li>';
				}
				for ($i=1; $i <= $page->total_pages; $i++) { 
					if ($i == $page->current) {
						echo '<li><span class="current">'.$i.'</span></li>';
					} else {
						echo '<li><a href="'.base_url().'danh-muc/'.$category->id.'-'.$this->string->replace($category->name).'?page='.$i.'">'.$i.'</a></li>';
					}
				}
				if ($page->current == $page->last) {
					echo '<li><i class="fa fa-chevron-right"></i></li>';
				} else {
					echo '<li><a href="'.base_url().'danh-muc/'.$category->id.'-'.$this->string->replace($category->name).'?page='.$page->next.'"><i class="fa fa-chevron-right"></i></a></li>';
				}
			 ?>
		</ul>
	</nav>

</section> <!-- / #ccr-category-2 -->